#!/bin/bash

sudo yum install -y wget unzip || sudo apt install -y wget unzip
sudo wget https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
sudo unzip terraform_0.12.2_linux_amd64.zip 
mv terraform /usr/local/bin/
